version: '3.8'

services:
  postgres10:
    image: postgres:13
    container_name: payslip-postgres
    ports:
      - "5610:5432"
    environment:
      POSTGRES_DB: payslip_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    container_name: payslip-backend
    ports:
      - "3610:3610"
    depends_on:
      - postgres10
    environment:
      DB_HOST: postgres10
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: admin123
      DB_NAME: payslip_db

  employee-side:
    build: ./Employee-Side
    container_name: payslip-employee
    ports:
      - "8618:80"
    depends_on:
      - backend

  hr-side:
    build: ./HR-Side
    container_name: payslip-hr
    ports:
      - "8619:80"
    depends_on:
      - backend

volumes:
  pgdata:

